# Generated by Django 5.1 on 2026-01-28 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_likedsong_recentlyplayed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='release_date',
        ),
    ]
